### ISSUE TITLE
Outlook - Launch HTML form in custom task pane

### ISSUE THREAD

**Issue by ManojPatel1983** [stever/AppHostCefSharp#2]
Hello,

I have outlook plugin (outlook 2010) where I want to launch HTML form in the custom task pane and for that thought to use chromium browser.
But looks like CefSharp doesn't provide multiple AppDomains so probably it will not work based on this link
https://github.com/cefsharp/CefSharp/issues/351
 
However, I saw "AppHostCefSharp" approach and the sample project uploaded for ExcelDNA which looks promising but in #351 it's mentioned about _"Trouble with RedGate.AppHost is the one-way communication"_ My requirement is to implement 2 way communication so Outlook and HTML form can share the data required.
Also, the HTML form will be displayed on the Custom Task Pane (CTP) so with email window both outlook and form should get displayed.

With this approach do you see any issue with my requirement of 2 way communication and display form in the same screen ?

Thanks!

**Comment by stever** [comment]
Hello

I've no idea how you would do this in Outlook. I've used Excel-DNA, which is for Excel only, and it helps a lot with the process integration. A named-pipe was added to the example in this repository which helps, but it's still one-way really. I'd been using an embedded HTTP server before then. It's still complicated with both parts being in separate processes.

**Comment by ManojPatel1983** [comment]
Hi, Thanks for your response.
Can you please confirm whether this AppHostCefSharp approach would resolve issue 
https://github.com/cefsharp/CefSharp/issues/1191  "CefSharp with Outlook 2010 VSTO Add-in  #1191 ".

If yes then probably I should be able to use that. With CefSharp I could launch HTML form in winform and implement 2 way communication. So  I want similar thing with Outlook but I saw CefSharp issue with Outlook 2010 VSTO Add-in so looking for an alternate option which can fix this issue and can support 2 way communication.

Thanks.

**Comment by stever** [comment]
You certainly won't enjoy the same 2-way communication that you can get with CefSharp without the AppDomain issue. There may be workarounds, such as using a Web Socket server.

I am not sure if the named pipe solution can be used for duplex communications. It seems there might be potential for that according to [this link](https://stackoverflow.com/questions/16432813/async-two-way-communication-with-windows-named-pipes-net) but can't say that will work with RedGate AppHost. Could be worth a go.

Web Socket is probably fairly easy, but then in all these cases there is a potential problem with administrator requirement on reserving ports or named pipes, and security considerations. Fleck seems pretty good for Web Socket implementation in C#. Restrict to local connections only is a good start.

**Comment by ManojPatel1983** [comment]
Thanks. looks like it would be difficult to implement this with outlook - launch form and 2 way communication.

I tried the approach suggested by flole (#1556) about to get the default appDomain and initialize ChromiumWebBrowser (this is using CefSharp). That way I can instantiate the Chromium control but not able to add it to my Winform as again it's from a different AppDomain so throws error "Remoting cannot find field 'parent' on type 'System.Windows.Forms.Control'.".

https://github.com/cefsharp/CefSharp/pull/1556
